# Generated by Django 3.1 on 2020-08-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
