# Generated by Django 3.1 on 2020-08-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20200805_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='question',
            field=models.CharField(max_length=40),
        ),
    ]
